name: test scss compile

on:
  workflow_dispatch:
  push:
    branches:
      - add-scss-compile

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git pull origin main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install SCSS Compiler and Bootstrap
        run: |
          cd ops
          npm install

      - name: Compile SCSS
        run: |
          cd ops
          npm run sass

      - name: Replace GA_MEASUREMENT_ID in HTML files
        run: find ./ -type f -name "*.html" -exec sed -i 's/GA_MEASUREMENT_ID/${{ secrets.GA_MEASUREMENT_ID }}/g' {} \;

      - name: Archive compiled files
        uses: actions/upload-artifact@v2
        with:
          name: compiled-files
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download compiled files
        uses: actions/download-artifact@v2
        with:
          name: compiled-files

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          rsync -av --delete ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/test_deploy/

      - name: Reload NGINX
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo /usr/sbin/nginx -s reload"
